#!/bin/bash
#SBATCH --job-name=LESBL
#SBATCH --ntasks=24
#SBATCH --ntasks-per-core=1
#SBATCH --time=24:00:00
#SBATCH --mincpus=12
#SBATCH --mem-per-cpu=6GB
#SBATCH -p q24,q36,q64
#SBATCH --exclusive

srun ./LES2
